spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_order
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: OrderConfirmationEvent:cc.elefteria.order_service.kafka.OrderConfirmationEvent  

server:
  port: 8070

application:
  config:
    customer-url: /api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: /api/v1/payments
  