services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data #'postgres' is a volume that would be managed by docker and exists on path: /var/lib/docker/volumes/micro-shop_postgres
    ports:
      - 5432:5432
    networks:
      - micro-shop-net # network from 'networks' section
    restart: unless-stopped
  
  mongodb:
    container_name: ms_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data #'mongo' is a volume that would be managed by docker and exists on path: /var/lib/docker/volumes/micro-shop_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
  
  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  
  ms_zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ms_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - micro-shop-net
        
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - 9092:9092
    depends_on:
      - ms_zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 #how many clusters of the kafka
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 #how many clusters of the kafka
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 #how many clusters of the kafka
      KAFKA_ZOOKEEPER_CONNECT: ms_zookeeper:2181 #zookeeper address
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT #which protocol to use for each listener <name:value> format
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # address of the listeners <name:address> format
    networks:
      - micro-shop-net

networks:
  micro-shop-net:
    driver: bridge
      
volumes:
  postgres:
  mongo: